on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  python:
    uses: rssnyder/actions/.github/workflows/python-poetry.yml@main
  docker:
    needs: python
    uses: rssnyder/actions/.github/workflows/docker-build-and-push.yml@main
